service: text-notifications

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment:
    TWILIO_ACCOUNT_SID: 
    TWILIO_AUTH_TOKEN: 
    TWILIO_PHONE_NUMBER: 
    GOOGLE_RECAPTCHA_TOKEN: 

functions:
  validateRecaptchaSendSms:
    handler: handler.validateAndSend
    events:
      - http:
          path: api/sendSms
          method: post
          integration: lambda
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: tnez-node-text-app-20180807
